config/routes.rb
Rails.application.routes.draw do
  get 'favorites/update'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root 'posts#index'
  get 'posts/:id/edit', to: 'posts#edit', as: :edit_post
  patch 'posts/:id', to: 'posts#update'
  delete 'posts/:id', to: 'posts#destroy', as: :delete_post
  resources :posts, only: [:index, :new, :create]
  get 'posts/:id' ,to: 'posts#show', as: :post

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_one_attached :image
  has_one_attached :file
  has_one_attached :clip
  has_many_attached :thumbnail_videos
  belongs_to :user
  validates :user, presence: true
  validates :title, presence: true, length: {maximum: 100}
  validates :body, presence: true
  # validates :image, content_type: ['image/png', 'image/jpg', 'image/jpeg'], size: { less_than: 5.megabytes, message: 'is too large' }
  validates :image , content_type: ['image/png', 'image/jpeg'], size: {less_than: 20.megabytes, message: 'is too large'}

  def image_thumbnail
    return self.image.variant(resize_to_limit: [300, 300]).processed if self.image.attached?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def favorite_text
        return @favorite_exists ? 'Favorited' : 'Favorite'
    end

    helper_method :favorite_text
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def update
    favorite = Favorite.where(post: Post.friendly.find_by(slug: params[:post]))
    if favorite.empty?
      Favorite.create(post: Post.friendly.find_by(slug: params[:post]), user: current_user)
      @favorite_exists = true
    else
      favorite.destroy_all
      @favorite_exists = false
    end

    respond_to do |format|
      format.js   # for AJAX/JS
      format.html { redirect_back fallback_location: post_path(params[:post]) }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update , :destroy]
  before_action :authenticate_user!, except: [:index, :show , :create , :new]
  def index
    @posts = Post.all.order(created_at: :desc).paginate(page: params[:page], per_page: 2)
  end

  def background
    our_input_text = " background process"
    @text = `python lib/assets/background.py "#{our_input_text}" `
  end

  def new
    @post = Post.new
  end

  def show
    @favorite_exists = Favorite.where(post: @post, user: current_user).exists? ? false : true
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post), notice: 'Post updated successfully.'
    else
      render :edit, alert: 'Error updating post.'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: 'Post deleted successfully.'
  end

  # def create
  #   @post = Post.new(post_params)
  #   @post.user = current_user 
  #   if @post.save 
  #     redirect_to posts_path, notice: 'Post created succesfully.'
  #   else
  #     flash.now[:alert] = @post.errors.full_messages.to_sentence
  #     puts @post.errors.full_messages
  #     # render :new, alert: @post.errors.full_messages.to_sentence
  #     redirect_to new_post_path, alert: @post.errors.full_messages.to_sentence

  #   end
  # end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to posts_path, notice: 'Post created successfully.'
    else
      # flash.now[:alert] = @post.errors.full_messages.to_sentence
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_post
    @post = Post.friendly.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body , :image , :file , :clip , thumbnail_videos: [])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/favorites/update.js.erb
$('#favorite_link').text('<% j favorite_text %>');

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_navbar.html.erb
<% if current_user %>
    <%= button_to 'Sign Out' , destroy_user_session_path , method: :delete %>
<%else%>
    <%= link_to 'Sign Up' , new_user_registration_path %>
    <%= link_to 'Sign in', new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails5</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <%= javascript_importmap_tags %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"></script>
</body>
  </head>

  <body>
    <%= render 'layouts/alerts' %>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f|%>
    <% if flash[:alert] %>
        <div class="alert alert-danger"><%= flash[:alert] %></div>
    <% end %>
    <%= f.input :title%>
    <%= f.input :body%>
    <%= f.input :image, as: :file %>
    <%= f.input :file, as: :file %>
    <%= f.input :clip, as: :file %>
    <%= f.input :thumbnail_videos, as: :file, input_html: { multiple: true } %>
    <%= f.button :submit %>
<%end%>

app/views/posts/edit.html.erb
<h1>Edit post</h1>
<%= simple_form_for(@post) do |f|%>
    <%= f.input :title %>
    <%= f.input :body %>
    <%= f.button :submit, "Update Post" %>
<%end%>

app/views/posts/index.html.erb
<h1>Posts Page</h1>

<%= link_to "New post" , new_post_path %>

<% @posts.each do |post|%>
    <p>[<%= post.id %>]<%= post.title%></p>
    <p><%= post.body%></p>
    <% if post.image.attached? %>
        <p><%= link_to image_tag(post.image_thumbnail) , post %></p>
    <% end %>
    <%= link_to "Show" , post%>
    <%= link_to "Edit post" , edit_post_path(post) %>
    <%= link_to "Delete" , delete_post_path(post)%>
<% end%>

<%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1>Create New Post</h1>
<%= render 'posts/form'%>

app/views/posts/show.html.erb
<h1>Showing post</h1>
<h3><%= @post.title%></h3>
<%= link_to favorite_text, favorites_update_path(post: @post), id: "favorite_link" %>
<p><%= @post.body%></p>
<p><%= @post.user.email %></p>
<% if @post.image.attached? %>
    <p><%= image_tag(@post.image_thumbnail) %></p>
<% end %>
<% if @post.file.attached? %>
    <p><%= link_to 'Download' , @post.file , download: '' %>
<% end %>

<% if @post.clip.attached? %>
    <p><%= video_tag(url_for(@post.clip), controls: true, size: "320x240") %></p>
<% end %>


<%= link_to "All Posts", posts_path%>
<%= link_to "Edit post" , edit_post_path(@post) %>
<%= link_to "Delete", delete_post_path(@post), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>